# Generated by Django 5.2.13 on 2026-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Math', 'Math'), ('Logic', 'Logic'), ('Memory', 'Memory'), ('Riddle', 'Riddle'), ('Word', 'Word')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
